"""add summary_generated_at to stories

Revision ID: 0268dc4f154c
Revises: b9c333ecc889
Create Date: 2026-04-30 04:21:35.280751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0268dc4f154c'
down_revision = 'b9c333ecc889'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary_generated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.drop_column('summary_generated_at')

    # ### end Alembic commands ###
