"""add scrape_audited to article

Revision ID: 036ef249a62b
Revises: 913e5418ffa8
Create Date: 2026-04-19 04:47:01.395563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '036ef249a62b'
down_revision = '913e5418ffa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scrape_audited', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('scrape_audited')

    # ### end Alembic commands ###
