"""add allsides_bias_score and bias_source to outlet

Revision ID: 0cc638e37c46
Revises: e8180f6deeba
Create Date: 2026-04-19 02:33:39.728742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cc638e37c46'
down_revision = 'e8180f6deeba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outlets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allsides_bias_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('bias_source', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outlets', schema=None) as batch_op:
        batch_op.drop_column('bias_source')
        batch_op.drop_column('allsides_bias_score')

    # ### end Alembic commands ###
