"""Add bias_mode to Topic and rename allsides_bias_score to static_bias_score

Revision ID: 0ee4dbd42d1b
Revises: c99ec9106d5b
Create Date: 2026-07-09 21:50:29.932204

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0ee4dbd42d1b'
down_revision = 'c99ec9106d5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outlets', schema=None) as batch_op:
        batch_op.alter_column('allsides_bias_score', new_column_name='static_bias_score')

    op.execute("UPDATE outlets SET bias_source = 'static' WHERE bias_source = 'allsides'")

    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bias_mode', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_column('bias_mode')

    with op.batch_alter_table('outlets', schema=None) as batch_op:
        batch_op.alter_column('static_bias_score', new_column_name='allsides_bias_score')

    op.execute("UPDATE outlets SET bias_source = 'allsides' WHERE bias_source = 'static'")

    # ### end Alembic commands ###
