"""add editions and edition_stories

Revision ID: 913e5418ffa8
Revises: 0cc638e37c46
Create Date: 2026-04-19 02:57:16.571098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '913e5418ffa8'
down_revision = '0cc638e37c46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('editions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('edition_type', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'edition_type', name='uq_edition_date_type')
    )
    op.create_table('edition_stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edition_id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('headline_score_at_publish', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['edition_id'], ['editions.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('edition_stories')
    op.drop_table('editions')
    # ### end Alembic commands ###
