"""unique edition story constraint

Revision ID: b9c333ecc889
Revises: 036ef249a62b
Create Date: 2026-04-30 04:16:05.621487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9c333ecc889'
down_revision = '036ef249a62b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edition_stories', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_edition_story', ['edition_id', 'story_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edition_stories', schema=None) as batch_op:
        batch_op.drop_constraint('uq_edition_story', type_='unique')

    # ### end Alembic commands ###
