"""add_topic_display_fetch_prompt_columns

Revision ID: c99ec9106d5b
Revises: 1f2e3d4c5b6a
Create Date: 2026-07-07 21:16:42.607524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c99ec9106d5b'
down_revision = '1f2e3d4c5b6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('icon', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('display_order', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
        batch_op.add_column(sa.Column('fetch_mode', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('fetch_country', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('fetch_category', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('fetch_query', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('gnews_query', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('gnews_category', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('analysis_persona', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('analysis_keywords_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('classifier_hint', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('summary_prompt', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('deep_report_prompt', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_column('deep_report_prompt')
        batch_op.drop_column('summary_prompt')
        batch_op.drop_column('classifier_hint')
        batch_op.drop_column('analysis_keywords_json')
        batch_op.drop_column('analysis_persona')
        batch_op.drop_column('gnews_category')
        batch_op.drop_column('gnews_query')
        batch_op.drop_column('fetch_query')
        batch_op.drop_column('fetch_category')
        batch_op.drop_column('fetch_country')
        batch_op.drop_column('fetch_mode')
        batch_op.drop_column('is_active')
        batch_op.drop_column('display_order')
        batch_op.drop_column('icon')
        batch_op.drop_column('description')
        batch_op.drop_column('label')

    # ### end Alembic commands ###
